version: 2
updates:
  # npmパッケージの依存関係を管理
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "21:00"
      timezone: "Asia/Tokyo"
    # PRの設定
    open-pull-requests-limit: 10
    versioning-strategy: auto
    labels:
      - "dependencies"
    allow:
      # Next.js関連
      - dependency-name: "next"
      - dependency-name: "next-themes"
      # React関連
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "@types/react"
      - dependency-name: "@types/react-dom"
