version: 2
updates:
  # npmパッケージの依存関係を管理
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "21:00"
      timezone: "Asia/Tokyo"
    # PRの設定
    open-pull-requests-limit: 10
    versioning-strategy: auto
    labels:
      - "dependencies"
    allow:
      # Next.js関連
      - dependency-name: "next"
      - dependency-name: "next-themes"
      # React関連
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "@types/react"
      - dependency-name: "@types/react-dom"
      # データベース関連
      - dependency-name: "@prisma/client"
      - dependency-name: "prisma"
      # UI関連
      - dependency-name: "lucide-react"
      # 開発ツール関連
      - dependency-name: "husky"
      - dependency-name: "lint-staged"
      - dependency-name: "vitest"
      # 認証関連
      - dependency-name: "next-auth"
    # React系のパッケージの更新はまとめて実施
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
        update-types:
          - "major"
          - "minor"
          - "patch"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/client"
        update-types:
          - "major"
          - "minor"
          - "patch"
