-- CreateTable
CREATE TABLE `Book` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `author` VARCHAR(191) NULL,
    `pagesRead` INTEGER NULL,
    `totalPages` INTEGER NULL,
    `purchasedAt` DATETIME(3) NULL,
    `startedAt` DATETIME(3) NULL,
    `finishedAt` DATETIME(3) NULL,
    `note` VARCHAR(191) NULL,
    `status` ENUM('CONSIDERING_PURCHASE', 'PURCHASED_UNREAD', 'READING', 'COMPLETED') NOT NULL DEFAULT 'CONSIDERING_PURCHASE',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
